// Package Swagger provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/pseudo-su/oapi-ui-codegen DO NOT EDIT.
package Swagger

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"github.com/getkin/kin-openapi/openapi3"
	"strings"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{
	"H4sIAAAAAAAC/8xX627buBJ+FR6eA5xdrG1d7KSJ/gVp0WZ7SZEaWKBFEVDiSGJLkSxJ2TECv/uClOQ4",
	"luxk02DR/IrF4Xzf3Ie3OJOVkgKENTi5xSYroSL+33NioZCagf/FLFT+n/9pyHGC/xvcXQzaW8F7sIQS",
	"S/B6hO1KAU4w0Zqs3O9XWkvtFCgtFWjb6oXuMwWTaaYskwInzWdUgTGkADzCcEMqxZ3CTNacIiEtMmSF",
	"SuBc4g2asZqJAq/XI6zhR800UJx8aUG+bsRk+g0y61i9AcJt2aeVlZB9f7zhjZpzdwn0kPXGEm2vLaug",
	"b+u8BOTPESUWEBEUOUEkc3T28QLpWghn1LYT4jAOx+HxOIrmUZTMTpM4mhzF4Wkcf+47w6Pb2uxFtrVx",
	"YLYEB+iARF05v12+xSP819nVh4sPr/EIn19dzC/Oz95tefIOo1b7rWvOWoPuGTKdHUXHQ5QXoI1XsBuZ",
	"tGacHvCkP+97csu4QS/G3ovhH2GUhOEQoYLZ60xWFbPDuAWzqDlHJTHlPswXWZxDmuZxehKdRC+Ooiie",
	"vTihszxPCU0BovT4aJYfT4cocCKK2tXDIAGlZaFJVTFRoE4S1QYoshIxB1+BsD1ChTwEdb0Vhz5ke9jZ",
	"+mQG0SSaTaYPpMFB+F2d0SSchIN9YacFrPc2ha6aexnIibHXvkG47jJEzEmg0mtBXnA4H+HGghaEIwN6",
	"wTI4XOJH4WQ6DcOT08/DATP2OieM1xoOkHISQH+eW3Q6Dk/Hcey5nSRH0ST0f9F+cqbOMjDmALlWIq/5",
	"v+y8bs4MUmsPdxrlQfhKikLSFDGDfAvtAQqyr325E4exq7+po3S106FbpMGO/PiuP2TMPx4Bw5XEubwC",
	"o6Qw0K+kvX5/3/pcg621aAz3ox4tpeYUgaBKMmHved2DjRqJ/zy4E3TYQ1vBZo/p7wWSerp7I9qPAq+L",
	"gYP1Adj9Dns2+BG2JOXw4GIzb6QG6c43GnZI3lscD2nfWjGfxYXuExO57CfUqxsFmrnxQzgiSnGWEXeE",
	"cqkRhQVwqdzYOr8Izl8ixRRwJlwdcJZBG4qGH75UINBruQAt/Dh75yQyQIupnzi15jjBpbUqCYLlcjkR",
	"HohworOSLcBMCrmY1N8DKrNAKhDjYqNrzBtdQTvZgmngQ8WsT3CqxjkTdMyEYUVpzVjJbEwUw1tzsp18",
	"6xF2ut1hgqftMFTElj4mAYVF4OspuHUJZ8Cu3fcC/HKjiCYVWNAGJ192Pdk1KEqsAesm+48a9GqEpEbm",
	"OxNihV0QcOLhcBdW3OLg7Sq0uoZR++YYDPBto8kj3KnScmnw9r3Njt7P8nt7+D6FmeTPqzBN5Q1+gmUF",
	"SC/5nFy4bFL9KXw0oaw2QzeZsFC4t86+q0ryVfE0VFdxtfEN6uD1ry6XmlbpHRSHYdMkhQXhM9nCjQ0y",
	"s8CJqDl37YFCTmpud+S2OkLwzTT75h3uoRbWPGvXjertOnEO2sxU0AhawRE2dVURversRo25bmCRwlUc",
	"VnXKWYa/OuGg3LxQ2+q8D3PlJ6TpFqbea87vTc1rFkmBKCgQ1LWtdtQb/KAT+85xzhw90kHtC7vvoE+b",
	"bY+v2kHv1qXOhCXr9j9vzgDx9QjP4tNni+SGaJ9pi4iWRPvHTa2QHxuFJhQo+o1YxMFtsFJAu7Mygdqt",
	"yYl2a1Nr3O/4V8vELo3OPl78fyeZthKTyi4rq60N6WBeGv/uQ3OpWOYXBtQO/RV66e4/Ifse65DeOjXg",
	"m8u3v1woXoNFmwV0T1MwS1IUzdt00PtGQfbUwu6R7kJJ0J+fLj+4jalqGgwzKGccdvi32B1v//Me65r9",
	"JG/f1Utb8QcIb/DQm/n7d57447iu138HAAD//0wx0IUYFQAA",
}

// GetOpenAPISpec returns the Swagger specification corresponding to the generated code
// in this file.
func GetOpenAPISpec() (*openapi3.T, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewLoader().LoadFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
