// Package Swagger provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/pseudo-su/oapi-ui-codegen DO NOT EDIT.
package Swagger

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"github.com/getkin/kin-openapi/openapi3"
	"strings"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w7+2/bOJr/CqE7oMmcIusty0B/yHZ63d50mtm2iwV2XBS09NnmViI1JBXXGOR/P3zU",
	"w7ItO0knvesutr9UFqnv/eTH/G5loqwEB66VNfvdUtkaSmoeX1ANKyEZmF9MQ2ke/lPC0ppZ/zHZfThp",
	"v5p8kKwqQFt3tqW3FVgzi0pJt/j7pZRC4veVFBVI3YKF7nUOKpOs0kxwa9a8JiUoRVdg2RZ8oWVVIMBM",
	"1EVOuNBE0S1ZQ1EIq8emtGR8Zd3d2ZaE32omIbdmv7ZIPvbbxOIfkBkq/wy00OtjsrI1ZJ8fzncD5gV+",
	"BHKMe6Wp1J80K+GY1w9rIGad5FQDoTwnuJGIJbn+5TWRNefI1FAIvuu7V2585XkfPG8WpjPfcyLfTX3/",
	"78fCMNh1rU5i1rVCZHoNiBAR8bpEud38ZNnW367fvX399pVlWy/evf7w+sX1m4Ekdzjq6jR3zVrL0B4j",
	"QRh58RjJtyCVAXComUXNivyMJM36sSQHzI1K0TdSdP/L9WauO0bQiulPmShLpsfxrpgmzTpZU7U+hTPJ",
	"/CUsFkt/MfWmXhJ5nh8m0zxcLhc0XwB4izgKl3EwRkJB+apGfxgloJJiJWlZMr4i3U5SK8iJFoQh+hK4",
	"PiJoJc6h+jTQwzHKdrHj9asp8BwvdIJ7zOAs+kOYnuM67mhcOAgBdyeDQufNRxZYUKU/mQCB0WWMMNxB",
	"1gYKMRvH7RG+aJCcFkSBvGUZnHfxyHWCwHWn6d/HFab0pyVlRS3hDFG4A/I/TpuXXrnple8b2qazyHNc",
	"8887TZyqswyUOkNcu2NZF//HwuvyzChp7eJBoDyLvhR8JfIFYYqYEHqEkNNT4QtXEMch/MaPFtuDCN1i",
	"Go3ID4/6Y8w8OgWMedLPoGlONR1JsCI3EjgpmmN2ino1uqDpooD7S5Nm11ky34GqBFfw4Lzf8zeS8g3C",
	"Ecb3qqpzwAf11539pAITmhYPLuXGBPahF/nDykIjijEZtUi+nXmMRPw722J8KY4d478Zz8lrrthqrRV5",
	"BQJVa2owpgjtPXEpJPmtBrnFPJcBV7XCEEUnZWsN6KYrwFxYrbfkAknO+xcMFBGS3FLJRK1IJoTMGaca",
	"rhYUXRwhM1CXjmVbBUPwht+Gb+umAk5eiVuQ3OTSN7gjA3IbmHRXy8KaWWutq9lkstlsHE6RN1pQma3Z",
	"LShnJW6d+vMkF9lEVMCvVj2sq6KBNWnT6iSYGJUxbWJaXl0tGc+vWCufq0pkV7Ri1iBJt2n3zrYQNi7O",
	"rKDNxBXVa6PaSfa5BMrV5PctUHmHr1YwUlT9VYEi7V5CC/QEvS6xlAClWYk5gVNdS1qQhQT6uRKMa0UY",
	"NyFtxW6BD7VDWsfbkosfMqp/IBWVtAQN8tImc75khQbZlCqCF1sixUYZVSM0VUHGlmygxi1BsyIXP6xA",
	"4NMQnkPega4lV+R/3t+8JRum16RgSnfhds5L+oWVdUluaVGDIhfMAccs1VUFcsDPJfIDNFu3kiBZUSsN",
	"0iafYdtQuxB6TVoqTJbsGZ3zCwUY3U1eUpcOuakacyi2JKO8F2TDaGO6iNpIUaLpmBQhOOyAakEoF3qN",
	"NLCGn2c5u2U5fFpsn815LwZ0GlVXVYFiM4QsoBCbS2fOjTm025Q1+/VQ9S8ataF9OORFLSVwXWwJvaWs",
	"wFAym/Mr4rueZ0Ax/ATNy+rCg4VfWsMeUMsa7La5HUQJxjWssGO7s8ey5Kj5aEEyWmR1gRY4lNlSSAdl",
	"/vZP5ArTNenjAfDcaBO/RUF0xpAdszbEiaJ6QTlZwIzMOSFXRDG+KqA3G3BWDvnLe9/1X/7NdV3/stmF",
	"bQi9UoAy1pATE24R3+C7wWeBPf4cXs75nP9cFxqDNApA7YxcGQNaQK9imxhqcNfzAUnz2nX9+OBtMOe9",
	"kMSSSMpXI+wEjuMMqUGDenvzwWAUEhnr3LOLEp2cnZ1dmEC9M4yMamtoB336Ok6Se6lq3D6My4nlMCic",
	"M445v9aG3lKY4K3XgAIwEBWhEnaszRpNvrn+sX14f3ON2rjfHN5c//gYM3hz/aONwPd13YWTe9XdbnyO",
	"hBpN9y8MwSe00G56Qk3wulyAROaGQh/kCucEKZ+tx4WFi5tfPry+eXv95hIlfCI+oF1TRXLgosTcLiS5",
	"yKie9HHyEne1ARaNuLMZrCgMtDlvWLAJ40oDzRs/2TSrGGLYkpQD1+zNp1WOSRlUkw0rCtRbg9p0EDsq",
	"HHLDi+2c79uRyQXdnn2zdMju30nt9t+Oibavyz5ieG7KbaN233Wbwo9r4KYcoMhMZgqYyT9Ucwiwg7fr",
	"tlrqW6OyO6/oFDKb89/RIebWX957rteGJWtGzFt8b2zVmpFfmxeEuE4UBkHkx67nRbEbp4G9W0piN428",
	"aRxNkyAMI2+wlLqJ78VhGk7DKIjd6XApmQapnyZJ4iVJNPX7Ja95+Ij/3c35HfpheeCH9p6qH8rV9Y8H",
	"TKVeHE2nsRf7gZ+48ZCpNPYCf+qFfhJ5npvGe5QnfpyGfuKHSRwme/xO4zTyvCnKwfdcf7iUxkESJ0Ho",
	"xkmaeGnLpf39ydw+FGNwjxhdz5+mrhdGYRRN06nvpQOcru9HsZck/jRBdqI9gtwgDrzQ8xLPC1w/ifc+",
	"jMPY98I0jcJp4E+nQx69IAimket6cRS5rpv6D5Cm63ux60dekISJG4W+O5Snm/qhG/u+F7rTNI69aLDm",
	"B3GQ+NN0GvthFIV+MlgLoyByfT/x3DTx02k0XJvGSZD6UeKH/jQKg/jIrjFcdEF+KWRJNQYLUWNv2Ef5",
	"JpCPhP07+yASd0l/d2pkqto2+eYIwnfDg75CIQpBJKi60Bjqam52ho+MPue63WbSMUJxyRTGJmz/FjQv",
	"thhpsTVkvKp1G30t89WS1oX+9gRhnuvPfUASaDfalqrLksqtqZi6cqYTOHaMhHYdVpf2sPPYb45QqXSF",
	"9b1V1YuCZdZHBN31fyb9fdsm0KAgC9AbAE70RpxrC+fcNIZe28lhBzMh+Mbf7xWftlOc865XpHs94h/u",
	"EP8F2qy2jOJ1CbIvorwJquSSbNbASSVFXmfoUzt1nyvBn7w9O91meGern6+Rw2E5+c8iCf/xknhkY/WI",
	"NuNB6L9VN/F0Na9J9CdKphPl0olS6USZ5M35x3+n7H+VlN1lp5MJsR81NJGFTEgTW/DDLtU/MLsXQOVV",
	"RrM1DLL6PWav4YueVAVlByI69NYjcUBZ6S3poDeh0OAmhg7I92zt0Zoq4dtqSkIpboHQoiDAtZH/UoqS",
	"YEYFpRtWhpKW7JZqaEW9gpH6SVRgtMxf59bMegX6FYhHFAL2/1ch8Kq3rkzkYBNYkZduaobK4bmDJDMp",
	"euqDBl4Xxd335tavQO+mSBlhfCkIXYhaE8oJlUBPueS6v+Q0WmN3BWg7cz+6ENQMFcyFKCI4yaECngPX",
	"3UBMWV8pYfuBUmsvaR1L7f0wj8iWjZufOhbM4KUjfDlGOKYRP30y9faEHlPaYiQbKs39mLrCnJLDStIc",
	"cnJBNSmAYrXFob32wDhpB++4tZu8t8xdfndZpzOj619ePzswpoFh5qKzyq7ovK8F7OAiK6RZWhxMXgdV",
	"qQmfneFemesUyiY9xFsgmGtsY9NKyzrTtQRywbjGerlimbJJc6GAgM7MFPa776H+qqDtSs1kXz1HEIQt",
	"yVbUZEObcn5Nb4E8azY8Gyb83YDAyM6M9obrXS/d5VgzynvZzxRPROYhPWPheSFEAZQ/QVH8kPsZ/cWO",
	"Edu++cn6HiN9f7XkRFA38j72ne/eWH+9efvepHj18WKtdaVmkwlwZ8M+swpyRh0hVxP8Nbl5+/5TJnLG",
	"V5/UVmkoL/s6dniZQq+pRkufc2PqJh6YUexuVjY+KXvpes2dtUvc8aBpWf+J3T35/VNgwEBRsEoxNYCE",
	"9sRWtahVM+k8ADogxHGc9tlz9wdy5ozp3mkc7nreQ2sGcvvvhhhOVlX4yRPO5oaBulNWE5ae8gSiU/cp",
	"be/O9x+h78FH9mDOMnj+eq0PYJtBd/vrUPOZKB4ydheFej6AOND9STynz2xE8WT63whSCL6ySUH14LIT",
	"qSiTikioJCjguju4ElUlFMPOVUiO7IoloWSBPT9uWYgvrfQWC/HluZmMTO3Ic8I4iGzX8VwvaX6GiTlc",
	"/bBmqpmBKigg06bVOooeBQNTLJpUx9QePof8CbG2Yje3MHcjWRsrM8bRmBasuWvVVJ3NNZ99ryVUEUo2",
	"jZU15CCOvq0+fYiGzD7uFOtVO8Bv0rBq/pCgPUHRgtDunDo76Oo7NzpwISHH/QVF/Jg7De2Nht19hn/O",
	"GwfvaM5qZWrIQjTlAbkw97CQ4S47Xp41PGMmsgHU9lrGUdBP0Dl6yDaZc8N59+LA7FtXN5CeY2h3yBh9",
	"X2HAT2W+HQ2PM+F/C/lRQm5oe+Rtlmui4Lfa3CAVywcHakqyQiCLlSi2K1SLyePPmrfPSHPmiMwtmVS6",
	"ERH2tgdgyZyXtdIoMTM6oyVctl7eQn7uOu40DI0WpmmCEd73mp+p59pn47+9/61DjnLBnD8oG7S09EQ9",
	"lZaxYH28nlsi7vOl0bxu6iXT3f7BEzNzXpup2+/0pMzw3ZaHp/ontaGrVfPnPaPHDpggv/Zg64jo3YzX",
	"3AheClk28YgpTNFwQH+Lu6Pb/NyjumZ/kG6jwLUui3sI7vGRP3/4+Y0h/GG03t39bwAAAP//SziuRVo6",
	"AAA=",
}

// GetOpenAPISpec returns the Swagger specification corresponding to the generated code
// in this file.
func GetOpenAPISpec() (*openapi3.T, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewLoader().LoadFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
