// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ONSdigital/dp-find-insights-poc-api/metadata"
	"github.com/ONSdigital/dp-find-insights-poc-api/pkg/aws"
	"github.com/ONSdigital/dp-find-insights-poc-api/pkg/database"
	"github.com/ONSdigital/dp-find-insights-poc-api/pkg/geodata"
)

// Injectors from wire.go:

func InitService(maxmetrics geodata.MetricCount) (*Service, error) {
	clients := aws.ProvideAWS()
	password, err := database.ProvidePassword(clients)
	if err != nil {
		return nil, err
	}
	dsn := database.ProvideDSN(password)
	databaseDatabase, err := database.ProvideDatabase(dsn)
	if err != nil {
		return nil, err
	}
	geodataGeodata, err := geodata.ProvideGeodata(databaseDatabase, maxmetrics)
	if err != nil {
		return nil, err
	}
	metadataMetadata, err := metadata.ProvideMetadata(dsn)
	if err != nil {
		return nil, err
	}
	service := &Service{
		aws:      clients,
		pwd:      password,
		dsn:      dsn,
		db:       databaseDatabase,
		geodata:  geodataGeodata,
		metadata: metadataMetadata,
	}
	return service, nil
}
