// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package api

// Defines values for HealthStatus.
const (
	HealthStatusCRITICAL HealthStatus = "CRITICAL"

	HealthStatusOK HealthStatus = "OK"

	HealthStatusWARNING HealthStatus = "WARNING"
)

// Defines values for HealthCheckerName.
const (
	HealthCheckerNameMongodb HealthCheckerName = "mongodb"
)

// Defines values for HealthCheckerStatus.
const (
	HealthCheckerStatusCRITICAL HealthCheckerStatus = "CRITICAL"

	HealthCheckerStatusOK HealthCheckerStatus = "OK"

	HealthCheckerStatusWARNING HealthCheckerStatus = "WARNING"
)

// Error defines model for Error.
type Error struct {
	// error message
	Error string `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Checks *[]HealthChecker `json:"checks,omitempty"`

	// The start date and time of API running
	StartTime *string `json:"start_time,omitempty"`

	// The status of the API
	Status *HealthStatus `json:"status,omitempty"`

	// The uptime of API
	Uptime  *string `json:"uptime,omitempty"`
	Version *struct {
		// The build date and time of the API
		BuildTime *string `json:"build_time,omitempty"`

		// The git commit hash of the API
		GitCommit *string `json:"git_commit,omitempty"`

		// The programming language used to implement API
		Language *string `json:"language,omitempty"`

		// The version of the programming language used to implement API
		LanguageVersion *string `json:"language_version,omitempty"`

		// The version of API
		Version *string `json:"version,omitempty"`
	} `json:"version,omitempty"`
}

// The status of the API
type HealthStatus string

// HealthChecker defines model for HealthChecker.
type HealthChecker struct {
	// The last health check date and time of the external service
	LastChecked *string `json:"last_checked,omitempty"`

	// The last failed health check date and time of the external service
	LastFailure *string `json:"last_failure,omitempty"`

	// The last successful health check date and time of the external service
	LastSuccess *string `json:"last_success,omitempty"`

	// The message status of the external service
	Message *string `json:"message,omitempty"`

	// The name of external service used by API
	Name *HealthCheckerName `json:"name,omitempty"`

	// The status of the external service
	Status *HealthCheckerStatus `json:"status,omitempty"`
}

// The name of external service used by API
type HealthCheckerName string

// The status of the external service
type HealthCheckerStatus string

// HelloResponse defines model for HelloResponse.
type HelloResponse struct {
	// Message returned by hello world endpoint
	Message string `json:"message"`
}
