name: Component Tests
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgis:
        image: postgis/postgis
        env:
          POSTGRES_PASSWORD: insights
        ports: 
          - 54322:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.3 # ToDo - can you use 'latest' here?

      - name: Run Go Component Tests
        env:
          POSTGRES_PASSWORD: insights
        run: make test-comptestv