name: Nightly Integration Tests
on:
  schedule:
    - cron: '20 4 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Develop Branch
        uses: actions/checkout@develop

      - name: Setup Go
        uses: actions/setup-go@vs
        with:
          go-version: 1.17.3 # ToDo - can you use 'latest' here?

      - name: Run Go Integration Tests
        working-directory: ./inttests
        run: make testvv
